In [15]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [16]:
data = np.load('dataset.npy')

In [17]:
X = data[:, 1:]
y = data[:, 0]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
#PRE-DEFINED MODEL

In [19]:
model = KNeighborsClassifier()
model.fit(X_train, y_train)

KNeighborsClassifier()

In [20]:
model.predict(X_test[:10])

array([1, 7, 0, 9, 4, 5, 4, 6, 9, 2], dtype=uint8)

In [21]:
y_test[:10]

array([7, 7, 0, 9, 4, 5, 4, 6, 9, 2], dtype=uint8)

In [22]:
#INSIDE KNN ALGO.

In [23]:
class CustomKNN:
    """
    Custom K-Nearest Neighbors (KNN) classifier.

    Parameters:
    - n_neighbours (int, optional): The number of neighbors to consider for classification. Default is 5.

    Attributes:
    - n_neighbours (int): The number of neighbors to consider for classification.

    Methods:
    - fit(X, y): Train the KNN classifier with input data and labels.
    - predict_point(point): Predict the class of a single data point.
    - predict(X): Predict the classes of an array of data points.
    - score(X, y): Calculate the accuracy score of the classifier on the given data.

    Example usage:
    >>> knn = CustomKNN(n_neighbours=3)
    >>> knn.fit(X_train, y_train)
    >>> predictions = knn.predict(X_test)
    >>> accuracy = knn.score(X_test, y_test)
    """

    def __init__(self, n_neighbours=5):
        self.n_neighbours = n_neighbours

    def fit(self, X, y):
        """
        Train the KNN classifier with input data and labels.

        Parameters:
        - X (numpy.ndarray): The training data.
        - y (numpy.ndarray): The corresponding labels.
        """
        self._X = (X - X.mean()) / X.std()  # standardization
        self._y = y

    def predict_point(self, point):
        """
        Predict the class of a single data point.

        Parameters:
        - point (numpy.ndarray): The data point to classify.

        Returns:
        - int: The predicted class.
        """
        list_dist = []
        
        for x_point, y_point in zip(self._X, self._y):
            dist_point = ((point - x_point) ** 2).sum()
            list_dist.append([dist_point, y_point])
            
        sorted_dist = sorted(list_dist)
        top_k = sorted_dist[:self.n_neighbours]
        items, counts = np.unique(np.array(top_k)[:, 1], return_counts=True)
        ans = items[np.argmax(counts)]
        
        return ans

    def predict(self, X):
        """
        Predict the classes of an array of data points.

        Parameters:
        - X (numpy.ndarray): The array of data points to classify.

        Returns:
        - numpy.ndarray: An array of predicted classes.
        """
        results = []
        
        X = (X - X.mean()) / X.std()
        
        for point in X:
            results.append(self.predict_point(point))
            
        return np.array(results, dtype=int)

    def score(self, X, y):
        """
        Calculate the accuracy score of the classifier on the given data.

        Parameters:
        - X (numpy.ndarray): The input data for scoring.
        - y (numpy.ndarray): The true labels for scoring.

        Returns:
        - float: The accuracy score.
        """
        return sum(self.predict(X) == y) / len(y)


In [24]:
m2 = CustomKNN()
m2.fit(X_train, y_train)

In [ ]:
""" Comparing out custom made model's output with actual output """

In [27]:
print(m2.predict(X_test[:10]), y_test[:10], sep = '\n')

[1 7 0 9 4 5 4 6 9 2]
[7 7 0 9 4 5 4 6 9 2]


In [ ]:
""" Accuracy """

In [28]:
m2.score(X_test[:100], y_test[:100])

0.95